# tests/test_webauthn_rp.py
# S3.4: replay every GOLDEN/webauthn fixture through the real RP code
# (complete_registration / complete_assertion) and assert the closed-set
# outcomes. Fixtures are generated by scripts/make_webauthn_fixtures.py via real
# py_webauthn calls (R0.7) — never hand-written.

from __future__ import annotations

import base64
import json
from pathlib import Path

import pytest
from openstore.config import (
    CampaignSettings,
    DatabaseConfig,
    DiscordConfig,
    LLMSettings,
    MerchantConfig,
    RazorpayConfig,
    Settings,
    WebAuthnConfig,
)
from openstore.core.database import get_session, init_database
from openstore.core.webauthn_rp import (
    ChallengeStore,
    WebAuthnError,
    complete_assertion,
    complete_registration,
)
from openstore.models import WebAuthnCredential
from sqlmodel import select

GOLDEN = Path(__file__).resolve().parent.parent / "GOLDEN" / "webauthn"


def _load(name: str) -> dict:
    with open(GOLDEN / f"{name}.json") as f:
        return json.load(f)


@pytest.fixture()
def rp_settings() -> Settings:
    return Settings(
        merchant=MerchantConfig(name="Test"),
        razorpay=RazorpayConfig(key_id="k", key_secret="s"),
        discord=DiscordConfig(
            bot_token="t", buyer_trace_channel_id=1, merchant_trace_channel_id=2,
            money_trace_channel_id=3, alerts_channel_id=4,
        ),
        webauthn=WebAuthnConfig(rp_id="openstore.test", rp_name="x", origin="https://openstore.test"),
        database=DatabaseConfig(url="sqlite://"),
        llm=LLMSettings(),
        campaign=CampaignSettings(),
    )


@pytest.fixture()
def rp_session(rp_settings: Settings):
    init_database(rp_settings)
    s = get_session(rp_settings)
    yield s
    s.close()


# Map each registration fixture to the challenge key the fixture was built with
# (registration_rs256 -> rs256 challenge, etc.).
_REG_CHALLENGE_KEY = {
    "registration_es256": "es256",
    "registration_rs256": "rs256",
    "registration_eddsa_unsupported": "ed25519",
}
_ASSERTION_CHALLENGE_KEY = {
    "assertion_es256": "es256",
    "assertion_rs256": "rs256",
    "assertion_wrong_challenge": "es256",
    "assertion_sign_count_regression": "es256",
}


def challenge(name: str) -> str:
    key = _REG_CHALLENGE_KEY.get(name) or _ASSERTION_CHALLENGE_KEY.get(name)
    assert key is not None, f"no challenge key for {name}"
    return _load("_meta")["challenges"][key]


def _enroll(session, rp_settings, reg_name: str, user: str = "op1"):
    """Enrol a credential from a registration fixture. Returns the stored
    credential (credential_id / public_key used by later assertions)."""
    reg = _load(reg_name)
    store = ChallengeStore()
    store.issue(challenge(reg_name), {"mode": "policy"})
    return complete_registration(
        session, rp_settings, user, reg["credential_id"], reg["client_data_json"],
        reg["attestation_object"], challenge(reg_name), store=store,
    )


# --- enrolment -------------------------------------------------------------


def test_registration_es256_pass(rp_session, rp_settings):
    cred = _enroll(rp_session, rp_settings, "registration_es256")
    assert cred.credential_id == _load("registration_es256")["credential_id"]
    assert cred.sign_count == 3


def test_registration_rs256_pass(rp_session, rp_settings):
    cred = _enroll(rp_session, rp_settings, "registration_rs256")
    assert cred.sign_count == 1


def test_registration_eddsa_unsupported_alg(rp_session, rp_settings):
    reg = _load("registration_eddsa_unsupported")
    store = ChallengeStore()
    store.issue(challenge("registration_eddsa_unsupported"), {"mode": "policy"})
    with pytest.raises(WebAuthnError) as ei:
        complete_registration(
            rp_session, rp_settings, "op1", reg["credential_id"], reg["client_data_json"],
            reg["attestation_object"], challenge("registration_eddsa_unsupported"),
            store=store,
        )
    assert ei.value.reason_code == "webauthn_unsupported_alg"


def test_registration_challenge_single_use(rp_session, rp_settings):
    reg = _load("registration_es256")
    chal = challenge("registration_es256")
    store = ChallengeStore()
    store.issue(chal, {"mode": "policy"})
    complete_registration(rp_session, rp_settings, "op1", reg["credential_id"],
                          reg["client_data_json"], reg["attestation_object"], chal, store=store)
    with pytest.raises(WebAuthnError) as ei:
        store.consume(chal)
    assert ei.value.reason_code == "assertion_required"


def test_challenge_ttl_expiry(rp_settings):
    store = ChallengeStore(ttl_seconds=1)
    challenge = base64.urlsafe_b64encode(b"\x01" * 32).decode().rstrip("=")
    store.issue(challenge, {"mode": "policy"})
    import time as _time

    _time.sleep(1.05)
    with pytest.raises(WebAuthnError) as ei:
        store.consume(challenge)
    assert ei.value.reason_code == "assertion_required"


# --- assertion -------------------------------------------------------------


def test_assertion_es256_pass(rp_session, rp_settings):
    _enroll(rp_session, rp_settings, "registration_es256")
    f = _load("assertion_es256")
    store = ChallengeStore()
    store.issue(challenge("assertion_es256"), {"mode": "policy"})
    ok, new_count = complete_assertion(
        rp_session, rp_settings, "op1", f["credential_id"], f["client_data_json"],
        f["authenticator_data"], f["signature"], challenge("assertion_es256"),
        binding={"mode": "policy"}, store=store,
    )
    assert ok is True
    assert new_count == 4


def test_assertion_rs256_pass(rp_session, rp_settings):
    _enroll(rp_session, rp_settings, "registration_rs256")
    f = _load("assertion_rs256")
    store = ChallengeStore()
    store.issue(challenge("assertion_rs256"), {"mode": "policy"})
    ok, new_count = complete_assertion(
        rp_session, rp_settings, "op1", f["credential_id"], f["client_data_json"],
        f["authenticator_data"], f["signature"], challenge("assertion_rs256"),
        binding={"mode": "policy"}, store=store,
    )
    assert ok is True
    assert new_count == 2


def test_assertion_wrong_challenge(rp_session, rp_settings):
    _enroll(rp_session, rp_settings, "registration_es256")
    f = _load("assertion_wrong_challenge")
    store = ChallengeStore()
    # Issue the challenge the assertion was built against is NOT done here; the
    # fixture's expected_challenge is what the RP checks, and the signed challenge
    # differs -> must reject.
    store.issue(f["expected_challenge"], {"mode": "policy"})
    with pytest.raises(WebAuthnError) as ei:
        complete_assertion(
            rp_session, rp_settings, "op1", f["credential_id"], f["client_data_json"],
            f["authenticator_data"], f["signature"], f["expected_challenge"],
            binding={"mode": "policy"}, store=store,
        )
    assert ei.value.reason_code == "assertion_required"


def test_assertion_sign_count_regression(rp_session, rp_settings):
    _enroll(rp_session, rp_settings, "registration_es256")
    f = _load("assertion_sign_count_regression")
    # Simulate prior replays so the stored sign count equals the fixture's
    # received sign count (both 5) -> monotonicity must reject.
    cred = rp_session.exec(
        select(WebAuthnCredential).where(
            WebAuthnCredential.credential_id == f["credential_id"]
        )
    ).first()
    cred.sign_count = f["stored_sign_count"]
    rp_session.add(cred)
    rp_session.flush()

    store = ChallengeStore()
    store.issue(challenge("assertion_sign_count_regression"), {"mode": "policy"})
    with pytest.raises(WebAuthnError) as ei:
        complete_assertion(
            rp_session, rp_settings, "op1", f["credential_id"], f["client_data_json"],
            f["authenticator_data"], f["signature"],
            challenge("assertion_sign_count_regression"),
            binding={"mode": "policy"}, store=store,
        )
    assert ei.value.reason_code == "assertion_required"


def test_assertion_uv_flag_missing(rp_session, rp_settings):
    """Assertion whose authenticator_data lacks the UV bit rejects with
    assertion_required (no user_verified pathway is silently accepted)."""
    _enroll(rp_session, rp_settings, "registration_es256")
    f = _load("assertion_es256")
    auth_bytes = bytearray(base64.urlsafe_b64decode(f["authenticator_data"] + "=="))
    # Clear the UV bit (0x04) from the flags byte at index 32.
    auth_bytes[32] &= ~0x04
    auth_data = base64.urlsafe_b64encode(bytes(auth_bytes)).decode().rstrip("=")
    store = ChallengeStore()
    store.issue(challenge("assertion_es256"), {"mode": "policy"})
    with pytest.raises(WebAuthnError) as ei:
        complete_assertion(
            rp_session, rp_settings, "op1", f["credential_id"], f["client_data_json"],
            auth_data, f["signature"], challenge("assertion_es256"),
            binding={"mode": "policy"}, store=store,
        )
    assert ei.value.reason_code == "assertion_required"


def test_assertion_binding_mismatch(rp_session, rp_settings):
    """A cart-mode challenge completed with a policy binding (or mismatched
    cart_hash) rejects (PRD §3.5 e5)."""
    _enroll(rp_session, rp_settings, "registration_es256")
    cred = _load("registration_es256")
    f = _load("assertion_es256")
    store = ChallengeStore()
    store.issue(challenge("assertion_es256"), {"mode": "cart", "cart_hash": "hash-a"})
    with pytest.raises(WebAuthnError) as ei:
        complete_assertion(
            rp_session, rp_settings, "op1", cred["credential_id"], f["client_data_json"],
            f["authenticator_data"], f["signature"], challenge("assertion_es256"),
            binding={"mode": "cart", "cart_hash": "hash-b"}, store=store,
        )
    assert ei.value.reason_code == "assertion_required"


def test_assertion_binding_cart_match(rp_session, rp_settings):
    """A cart-mode challenge completed with the matching cart_hash passes."""
    _enroll(rp_session, rp_settings, "registration_es256")
    cred = _load("registration_es256")
    f = _load("assertion_es256")
    store = ChallengeStore()
    store.issue(challenge("assertion_es256"), {"mode": "cart", "cart_hash": "hash-a"})
    ok, _ = complete_assertion(
        rp_session, rp_settings, "op1", cred["credential_id"], f["client_data_json"],
        f["authenticator_data"], f["signature"], challenge("assertion_es256"),
        binding={"mode": "cart", "cart_hash": "hash-a"}, store=store,
    )
    assert ok is True
