# tests/test_compiler_goldens.py
# S3.2: replay every GOLDEN/compiler vector through compile_decision and assert
# byte-identical expected output, including the transcript (PoAI §3.3.6 / AAL e7).
# Sources: R0.7 — fixtures generated by scripts/make_compiler_goldens.py, never
# hand-written. Two vectors (policy.spend_envelope_exceeded,
# policy.aggregate_cap_exceeded) carry authored expected values for reason codes
# the root-path compiler cannot emit; they are validated for shape and routed to
# their behavioral gates (policy_signing for the aggregate cap).

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

from openstore.core.compiler import CompilerContext, compile_decision
from openstore.core.policy_signing import aggregate_cap_exceeds
from openstore.models import IntentPolicy

GOLDEN = Path(__file__).resolve().parent.parent / "GOLDEN" / "compiler" / "vectors.json"

# Reason codes the root-path compiler cannot produce this stage; their vectors are
# authored (expected pinned in the fixture) and dispatched to a signing-layer gate.
AUTHORED_ONLY = {"policy.spend_envelope_exceeded", "aggregate_cap_exceeded"}

AUTHORED_CODES = {
    "policy.aggregate_cap_exceeded",
}


def _load() -> list[dict]:
    with open(GOLDEN) as f:
        return json.load(f)


def _reconstruct_policy(pol: dict) -> IntentPolicy:
    return IntentPolicy(
        id=pol["id"],
        merchant_id=pol["merchant_id"],
        policy_version=pol["policy_version"],
        policy_hash=pol["policy_hash"],
        currency=pol["currency"],
        max_spend_per_tx_minor=pol["max_spend_per_tx_minor"],
        max_spend_total_minor=pol["max_spend_total_minor"],
        max_transactions=pol["max_transactions"],
        allowed_tags=pol["allowed_tags"],
        tag_mode=pol["tag_mode"],
        blocked_skus=pol["blocked_skus"],
        not_before=pol["not_before"],
        expires_at=pol["expires_at"],
        assertion_max_age_seconds=pol["assertion_max_age_seconds"],
        fulfilment_mode=pol["fulfilment_mode"],
        required_skus=pol["required_skus"],
        webauthn_credential_id=pol["webauthn_credential_id"],
        webauthn_sign_count=pol["webauthn_sign_count"],
        signed_at=datetime.fromisoformat(pol["signed_at"].replace("Z", "+00:00")),
        is_active=pol["is_active"],
    )


def _build_ctx(entry: dict) -> CompilerContext:
    pol = _reconstruct_policy(entry["policy"])
    ctx = entry["context"]
    return CompilerContext(
        cart_items=entry["cart"],
        policy=pol,
        merchant_id=ctx["merchant_id"],
        currency=ctx["currency"],
        checkout_count=ctx["checkout_count"],
        cumulative_spend_minor=ctx["cumulative_spend_minor"],
        has_webauthn_assertion=ctx["has_webauthn_assertion"],
        assertion_age_seconds=0,
        now_unix=ctx["now_unix"],
        campaign_lookup=ctx["campaign_lookup"],
    )


def test_vectors_present_and_sufficient():
    vectors = _load()
    assert len(vectors) >= 40
    required = [
        "allow_happy_path", "assertion_required", "policy.currency_mismatch",
        "policy.merchant_mismatch", "policy.policy_not_yet_valid", "policy.policy_expired",
        "policy.tx_count_exceeded", "policy.qty_invalid", "policy.sku_duplicate",
        "policy.sku_blocked", "policy.tag_violation_all", "policy.tag_violation_any",
        "policy.spend_per_tx_exceeded", "policy.spend_envelope_exceeded",
        "policy.spend_cumulative_exceeded", "policy.campaign_inactive",
        "policy.campaign_outside_window", "two_policy_cumulative_isolation",
        "aggregate_cap_exceeded",
    ]
    names = {v["name"] for v in vectors}
    for r in required:
        assert r in names, f"missing required vector {r}"
    # Names must be unique.
    assert len(names) == len(vectors)


def test_all_vectors_replay_byte_identical():
    vectors = _load()
    for entry in vectors:
        if entry["name"] in AUTHORED_ONLY:
            continue
        expected = entry["expected"]
        res = compile_decision(_build_ctx(entry))
        actual = {
            "allowed": res.allowed,
            "reason_code": res.reason_code,
            "transcript": res.transcript,
        }
        assert actual == expected, (
            f"vector {entry['name']} did not replay byte-identically\n"
            f"expected={json.dumps(expected, sort_keys=True)}\n"
            f"actual  ={json.dumps(actual, sort_keys=True)}"
        )


def test_failing_vectors_deny_with_reason_code():
    """Every single-check failure vector must deny with its exact reason code."""
    reason_by_vector = {
        "policy.currency_mismatch": "policy.currency_mismatch",
        "policy.merchant_mismatch": "policy.merchant_mismatch",
        "policy.policy_not_yet_valid": "policy.policy_not_yet_valid",
        "policy.policy_expired": "policy.policy_expired",
        "policy.tx_count_exceeded": "policy.tx_count_exceeded",
        "policy.qty_invalid": "policy.qty_invalid",
        "policy.sku_duplicate": "policy.sku_duplicate",
        "policy.sku_blocked": "policy.sku_blocked",
        "policy.tag_violation_all": "policy.tag_violation",
        "policy.tag_violation_any": "policy.tag_violation",
        "policy.spend_per_tx_exceeded": "policy.spend_per_tx_exceeded",
        "policy.spend_cumulative_exceeded": "policy.spend_cumulative_exceeded",
        "policy.campaign_inactive": "policy.campaign_inactive",
        "policy.campaign_outside_window": "policy.campaign_outside_window",
        "assertion_required": "assertion_required",
    }
    vectors = {v["name"]: v for v in _load()}
    for name, code in reason_by_vector.items():
        entry = vectors[name]
        res = compile_decision(_build_ctx(entry))
        assert res.allowed is False
        assert res.reason_code == code, f"{name}: got {res.reason_code}, want {code}"
        # Transcript stops at first failure: last entry carries the reason code.
        assert res.transcript[-1]["reason_code"] == code
        assert res.transcript[-1]["result"] == "fail"


def test_ordering_stop_at_first_failure():
    vectors = {v["name"]: v for v in _load()}

    # checks 4 AND 9 violated -> policy.policy_expired (stop at check 4).
    r_4_9 = compile_decision(_build_ctx(vectors["ordering_check4_before_check9"]))
    assert r_4_9.reason_code == "policy.policy_expired"
    assert r_4_9.transcript[-1]["check"] == "policy_expiry"

    # checks 1 AND 12 violated -> policy.currency_mismatch (stop at check 1).
    r_1_12 = compile_decision(_build_ctx(vectors["ordering_check1_before_check12"]))
    assert r_1_12.reason_code == "policy.currency_mismatch"
    assert r_1_12.transcript[-1]["check"] == "currency_match"


def test_two_policy_cumulative_isolation_spent_zero():
    """B (clean) passes check 11 with spent_minor scoped to 0 (PRD §3.2c)."""
    vectors = {v["name"]: v for v in _load()}
    entry = vectors["two_policy_cumulative_isolation"]
    assert entry["context"]["cumulative_spend_minor"] == 0
    res = compile_decision(_build_ctx(entry))
    assert res.allowed is True
    assert res.transcript[-1]["check"] == "campaign_validity"
    # Companion A vector proves A's own high cumulative breaches ITS budget.
    entry_a = vectors["two_policy_cumulative_spent_A"]
    res_a = compile_decision(_build_ctx(entry_a))
    assert res_a.allowed is False
    assert res_a.reason_code == "policy.spend_cumulative_exceeded"


def _aggregate_entry_policy():
    entry = next(v for v in _load() if v["name"] == "aggregate_cap_exceeded")
    return entry


def test_aggregate_cap_vector_shape_and_gate():
    """aggregate_cap_exceeded is a signing-time code; route it to the signing gate."""
    entry = _aggregate_entry_policy()
    assert entry["expected"]["allowed"] is False
    assert entry["expected"]["reason_code"] == "policy.aggregate_cap_exceeded"

    # Behavioral gate: a new policy whose max_spend_total pushes the enrolled user's
    # aggregate above the per-user cap is rejected with policy.aggregate_cap_exceeded.
    cap = 500_000
    # Fail: 450_000 already spent + 100_000 new budget = 550_000 > cap.
    assert aggregate_cap_exceeds(
        max_spend_total_minor=100_000,
        aggregate_spent_minor=450_000,
        per_user_aggregate_cap_minor=cap,
    ) is True
    # Pass: 200_000 spent + 100_000 new budget = 300_000 <= cap.
    assert aggregate_cap_exceeds(
        max_spend_total_minor=100_000,
        aggregate_spent_minor=200_000,
        per_user_aggregate_cap_minor=cap,
    ) is False


def test_authored_envelope_vector_shape():
    entry = next(v for v in _load() if v["name"] == "policy.spend_envelope_exceeded")
    assert entry["expected"]["allowed"] is False
    assert entry["expected"]["reason_code"] == "policy.spend_envelope_exceeded"
    assert entry["expected"]["transcript"] == []
    # The root compiler never emits this code: check 10 (spend_envelope) is
    # delegated-only and is skipped on the root path (PRD §3.2). The code is part
    # of the closed reason-code set but only enforced on delegated envelopes.
    from openstore.core.compiler import REASON_CODES
    assert "policy.spend_envelope_exceeded" in REASON_CODES
