"""the sidecar's own tables

Revision ID: 97715e29a1db
Revises:
Create Date: 2026-09-21 17:39:07.180050
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "97715e29a1db"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Every table the sidecar owns, as one first revision.

    Generated from the same `MetaData` the application uses, so the schema a
    deploy migrates to and the schema the code expects cannot be two different
    things. The Merchant's database is not here and never will be — the sidecar
    reaches Merchant truth only through the nine doors.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "baskets",
        sa.Column("agent_id", sa.String(length=128), nullable=False),
        sa.Column("cart_id", sa.String(length=64), nullable=False),
        sa.Column("lines", sa.Text(), nullable=False),
        sa.Column("destination", sa.Text(), nullable=False),
        sa.Column("contact", sa.Text(), nullable=False),
        sa.Column("fulfillment_option_id", sa.String(length=64), nullable=False),
        sa.Column("discount_code", sa.String(length=64), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("agent_id"),
    )
    op.create_table(
        "checkouts",
        sa.Column("order_id", sa.String(length=64), nullable=False),
        sa.Column("cart_id", sa.String(length=64), nullable=False),
        sa.Column("agent_id", sa.String(length=128), nullable=False),
        sa.Column("method", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("expiry_utc", sa.String(length=32), nullable=False),
        sa.Column("lines", sa.Text(), nullable=False),
        sa.Column("destination", sa.Text(), nullable=False),
        sa.Column("contact", sa.Text(), nullable=False),
        sa.Column("fulfillment_option_id", sa.String(length=64), nullable=False),
        sa.Column("discount_code", sa.String(length=64), nullable=True),
        sa.Column("quote", sa.Text(), nullable=False),
        sa.Column("quote_bytes_b64", sa.Text(), nullable=False),
        sa.Column("cart_hash", sa.String(length=64), nullable=False),
        sa.Column("total_minor", sa.Integer(), nullable=False),
        sa.Column("tap_token", sa.String(length=64), nullable=False),
        sa.Column("link_id", sa.String(length=128), nullable=False),
        sa.Column("payer_handle", sa.String(length=255), nullable=False),
        sa.Column("handle_source", sa.String(length=32), nullable=False),
        sa.Column("receipt_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("link_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("order_id"),
    )
    with op.batch_alter_table("checkouts", schema=None) as batch_op:
        batch_op.create_index("ix_checkouts_agent", ["agent_id"], unique=False)
        batch_op.create_index("ix_checkouts_link_id", ["link_id"], unique=False)
        batch_op.create_index("ix_checkouts_tap_token", ["tap_token"], unique=False)

    op.create_table(
        "ledger_entries",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("order_id", sa.String(length=64), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("closes_hold", sa.Boolean(), nullable=False),
        sa.CheckConstraint("amount_minor >= 0", name="ck_ledger_amount_non_negative"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_ledger_idempotency"),
    )
    with op.batch_alter_table("ledger_entries", schema=None) as batch_op:
        batch_op.create_index("ix_ledger_order", ["order_id"], unique=False)

    op.create_table(
        "passkey_ceremonies",
        sa.Column("tap_token", sa.String(length=64), nullable=False),
        sa.Column("verified", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("tap_token"),
    )
    op.create_table(
        "passkey_challenges",
        sa.Column("tap_token", sa.String(length=64), nullable=False),
        sa.Column("challenge", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("tap_token"),
    )
    op.create_table(
        "passkey_credentials",
        sa.Column("credential_id", sa.String(length=255), nullable=False),
        sa.Column("public_key", sa.Text(), nullable=False),
        sa.Column("sign_count", sa.Integer(), nullable=False),
        sa.Column("attestation_fmt", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("credential_id"),
    )
    op.create_table(
        "receipts",
        sa.Column("receipt_id", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("merchant_domain", sa.String(length=255), nullable=False),
        sa.Column("sealed_at", sa.String(length=32), nullable=False),
        sa.Column("stored_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("document", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("receipt_id"),
    )
    op.create_table(
        "refund_requests",
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("order_id", sa.String(length=64), nullable=False),
        sa.Column("agent_id", sa.String(length=128), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_note", sa.String(length=500), nullable=False),
        sa.PrimaryKeyConstraint("request_id"),
    )
    with op.batch_alter_table("refund_requests", schema=None) as batch_op:
        batch_op.create_index("ix_refund_order", ["order_id"], unique=False)
        batch_op.create_index(
            "uq_refund_open_per_order",
            ["order_id"],
            unique=True,
            sqlite_where=sa.text("state = 'requested'"),
            postgresql_where=sa.text("state = 'requested'"),
        )

    op.create_table(
        "resume_tokens",
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("order_id", sa.String(length=64), nullable=False),
        sa.Column("chat_thread_id", sa.String(length=128), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("spent", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("token"),
    )
    op.create_table(
        "tap_tokens",
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("order_id", sa.String(length=64), nullable=False),
        sa.Column("cart_hash", sa.String(length=64), nullable=False),
        sa.Column("total_minor", sa.Integer(), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("spent", sa.Boolean(), nullable=False),
        sa.Column("rendered_digest", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("token"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drops everything, the Ledger included.

    Present because alembic wants a pair and a one-way migration is a lie about
    what this file can do. **Nobody should run it on a deploy that has taken an
    order**: the Ledger is append-only and this is the one statement in the
    codebase that can delete it.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tap_tokens")
    op.drop_table("resume_tokens")
    with op.batch_alter_table("refund_requests", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_refund_open_per_order",
            sqlite_where=sa.text("state = 'requested'"),
            postgresql_where=sa.text("state = 'requested'"),
        )
        batch_op.drop_index("ix_refund_order")

    op.drop_table("refund_requests")
    op.drop_table("receipts")
    op.drop_table("passkey_credentials")
    op.drop_table("passkey_challenges")
    op.drop_table("passkey_ceremonies")
    with op.batch_alter_table("ledger_entries", schema=None) as batch_op:
        batch_op.drop_index("ix_ledger_order")

    op.drop_table("ledger_entries")
    with op.batch_alter_table("checkouts", schema=None) as batch_op:
        batch_op.drop_index("ix_checkouts_tap_token")
        batch_op.drop_index("ix_checkouts_link_id")
        batch_op.drop_index("ix_checkouts_agent")

    op.drop_table("checkouts")
    op.drop_table("baskets")
    # ### end Alembic commands ###
