from typing import Protocol
from reference.merchant.models import Product

class CatalogAdapter(Protocol):
    def get_product(self, sku: str) -> Product | None: ...
    def search_products(self, query: str) -> list[Product]: ...
    def list_all(self) -> list[Product]: ...