<?php
/**
 * Does the PHP implementation of §16.11 agree with the others, to the paise?
 *
 * Runs `pricing-vectors.json` — generated by the Python implementation — through
 * `OpenStore_Pricing` and compares every field. **No WordPress**: the pricing
 * class deliberately touches nothing but integers, so it can be checked without
 * a database, a site, or a plugin host.
 *
 *     docker run --rm -v "$PWD:/src" php:8.2-cli \
 *         php /src/integrations/woocommerce/tests/run-vectors.php
 *
 * A disagreement here is the whole reason this file exists. Two implementations
 * that round differently fire `quote-inconsistent` on a *correct* quote, which
 * looks like a bug in the money core and is actually a bug in one of them —
 * found here, on a laptop, instead of in a shop at the moment somebody taps.
 */

declare( strict_types=1 );

define( 'ABSPATH', __DIR__ );

require_once __DIR__ . '/../openstore-sidecar/includes/class-openstore-error.php';
require_once __DIR__ . '/../openstore-sidecar/includes/class-openstore-pricing.php';

$path = __DIR__ . '/pricing-vectors.json';
$doc  = json_decode( (string) file_get_contents( $path ), true );
if ( ! is_array( $doc ) || ! isset( $doc['cases'] ) ) {
	fwrite( STDERR, "could not read {$path}\n" );
	exit( 2 );
}

$failures = 0;
foreach ( $doc['cases'] as $case ) {
	$items = array();
	foreach ( $case['items'] as $item ) {
		$items[ $item['sku'] ] = array(
			'sku'         => $item['sku'],
			'price_minor' => (int) $item['price_minor'],
			'hsn_sac'     => (string) $item['hsn_sac'],
			'gst_rate_bp' => (int) $item['gst_rate_bp'],
			'tags'        => (array) $item['tags'],
		);
	}

	try {
		$got = OpenStore_Pricing::build_quote(
			$case['lines'],
			$items,
			(string) $case['destination_state'],
			(string) $case['home_state'],
			array(
				'id'         => (string) $case['zone']['id'],
				'label'      => (string) $case['zone']['label'],
				'cost_minor' => (int) $case['zone']['cost_minor'],
				'eta_days'   => (int) $case['zone']['eta_days'],
			),
			$case['discount'] ? array(
				'code'         => (string) $case['discount']['code'],
				'label'        => (string) $case['discount']['label'],
				'amount_minor' => (int) $case['discount']['amount_minor'],
			) : null,
			(bool) $case['tax_inclusive']
		);
	} catch ( Throwable $error ) {
		$failures++;
		printf( "FAIL  %s\n      threw: %s\n", $case['name'], $error->getMessage() );
		continue;
	}

	// Compared as canonical JSON: key order is not part of the claim, and every
	// value here is an integer, a string or a bool.
	$expected = canonical( $case['expected'] );
	$actual   = canonical( $got );
	if ( $expected === $actual ) {
		printf( "ok    %s\n", $case['name'] );
		continue;
	}

	$failures++;
	printf( "FAIL  %s\n", $case['name'] );
	foreach ( differences( $case['expected'], $got ) as $line ) {
		printf( "      %s\n", $line );
	}
}

printf( "\n%d case(s), %d failure(s)\n", count( $doc['cases'] ), $failures );
exit( $failures ? 1 : 0 );

/** Sort keys all the way down, so only values are compared. */
function canonical( mixed $value ): string {
	return (string) json_encode( sorted( $value ) );
}

function sorted( mixed $value ): mixed {
	if ( ! is_array( $value ) ) {
		return $value;
	}
	$out = array();
	foreach ( $value as $key => $item ) {
		$out[ $key ] = sorted( $item );
	}
	if ( ! array_is_list( $out ) ) {
		ksort( $out );
	}
	return $out;
}

/**
 * The fields that differ, named. A diff of two 40-line JSON documents is not a
 * finding; "total_minor: expected 104801, got 104800" is.
 *
 * @return string[]
 */
function differences( mixed $expected, mixed $actual, string $path = '' ): array {
	if ( is_array( $expected ) && is_array( $actual ) ) {
		$out  = array();
		$keys = array_unique( array_merge( array_keys( $expected ), array_keys( $actual ) ) );
		foreach ( $keys as $key ) {
			$out = array_merge(
				$out,
				differences(
					$expected[ $key ] ?? null,
					$actual[ $key ] ?? null,
					'' === $path ? (string) $key : "{$path}.{$key}"
				)
			);
		}
		return $out;
	}
	if ( $expected === $actual ) {
		return array();
	}
	return array(
		sprintf(
			'%s: expected %s, got %s',
			$path,
			var_export( $expected, true ),
			var_export( $actual, true )
		),
	);
}
