"""Canonical bytes, and the four hashes the money core is bound by.

SPEC §4 and SPECS/PLAN.md §6.3 fix the `cart_hash` preimage. This module is the
only place those bytes are produced, so "byte-identical across translators" is a
property of one function rather than of four implementations that agree today.

Frozen at hour 0. `tests/GOLDEN/cart_hash/vectors.json` pins the output and CI
compares it forever; changing anything here changes evidence bytes.
"""

from __future__ import annotations

import hashlib
import hmac
import json
from typing import Any

#: Canonical JSON: UTF-8, sorted keys, no whitespace, no non-finite floats.
#: `ensure_ascii=False` so a Devanagari city name hashes as its own bytes rather
#: than as an escape sequence — the two differ, and only one of them is what the
#: Consumer was shown.
_JSON_ARGS: dict[str, Any] = {
    "sort_keys": True,
    "separators": (",", ":"),
    "ensure_ascii": False,
    "allow_nan": False,
}


def canonical_bytes(obj: Any) -> bytes:
    """The one canonicalization. Every hash below is taken over this."""
    return json.dumps(obj, **_JSON_ARGS).encode("utf-8")


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def quote_hash(quote: dict[str, Any]) -> str:
    """`sha256` of the canonical Quote bytes.

    §6.3 says breakdown lines are "sorted by type then label". Each breakdown
    list has a different natural key, so the rule is applied per list and stated
    here rather than re-derived per implementation:

    - `lines` by `sku` (the Quote's own line identity)
    - `discount_lines` by `(code, label)`
    - `fulfillment_options` by `id`
    - `tax_lines` by `(kind, label)` — kind *is* the type for a tax line

    Sorting is by the values themselves, never by input order, so a Merchant
    that emits its tax lines in a different order still quotes the same bytes.
    """
    normalized = dict(quote)
    if "lines" in normalized:
        normalized["lines"] = sorted(normalized["lines"], key=lambda ln: ln["sku"])
    if "discount_lines" in normalized:
        normalized["discount_lines"] = sorted(
            normalized["discount_lines"], key=lambda d: (d.get("code", ""), d.get("label", ""))
        )
    if "fulfillment_options" in normalized:
        normalized["fulfillment_options"] = sorted(
            normalized["fulfillment_options"], key=lambda f: f["id"]
        )
    if "tax_lines" in normalized:
        normalized["tax_lines"] = sorted(
            normalized["tax_lines"], key=lambda t: (t["kind"], t.get("label", ""))
        )
    return _sha256(canonical_bytes(normalized))


def pii_commit(order_salt: bytes, pii: dict[str, Any]) -> str:
    """`HMAC-SHA256(order_salt, canonical PII bytes)` — a Destination or Contact
    Point commitment (ADR-0011).

    The salt is **128 bits, generated by the Merchant at `orders.create`, held in
    sidecar request memory only, and never written anywhere sidecar-side** (§6.3a).
    Erasure deletes the order row and the salt with it, and the commitment in the
    sealed bundle becomes permanently unopenable. A bare hash would not: a phone
    number is 10^10 guesses, which is no protection at all.
    """
    if len(order_salt) != 16:
        raise ValueError(f"order_salt must be 128 bits, got {len(order_salt) * 8}")
    return hmac.new(order_salt, canonical_bytes(pii), hashlib.sha256).hexdigest()


def cart_hash(
    *,
    lines: list[dict[str, Any]],
    quote_hash_hex: str,
    destination_hash: str,
    contact_hash: str,
    fulfillment_option_id: str,
    total_minor: int,
    currency: str,
    merchant_domain: str,
    expiry_utc: str,
) -> str:
    """The binding the Consumer's Authority is taken over (SPEC §4, §6.3).

    `fulfillment_option_id` and `total_minor` are in here because the Consumer
    authorizes the **delivered total**, not the item subtotal. Keyword-only on
    purpose: nine positional arguments of which four are hex strings is a
    preimage waiting to be assembled in the wrong order.
    """
    preimage = {
        "lines": sorted(
            (
                {"sku": ln["sku"], "qty": ln["qty"], "price_minor": ln["price_minor"]}
                for ln in lines
            ),
            key=lambda ln: ln["sku"],
        ),
        "quote_hash": quote_hash_hex,
        "destination_hash": destination_hash,
        "contact_hash": contact_hash,
        "fulfillment_option_id": fulfillment_option_id,
        "total_minor": total_minor,
        "currency": currency,
        "merchant_domain": merchant_domain,
        "expiry_utc": expiry_utc,
    }
    return _sha256(canonical_bytes(preimage))
