#!/usr/bin/env python3
"""Generate `tests/GOLDEN/cart_hash/vectors.json` — the frozen preimage.

Three cases, per SPECS/PLAN.md §12 hour 0 step 4:

1. `minimal` — one line, destination A (intra-state), the odd-paise CGST/SGST
   split that §16.11 step 6 exists for.
2. `mixed-basket` — the §16.11 worked example verbatim: destination B, a tote
   with gift-wrap folded in and a charm-bar seat, so one Quote carries IGST on
   one line and CGST/SGST on the other. **These numbers are pinned in §16.11;
   they are copied here, not recomputed.**
3. `with-discount` — `SPOILED10` across two lines at two different GST rates,
   exercising largest-remainder apportionment of both a discount and shipping.

The Quotes below are literal data, not computed: the Merchant's door 9 (B2) and
the Gate's `quote-consistent` (A3) must both reproduce them. That is what makes
these vectors a test rather than a tautology. The only arithmetic this script
does is the identity check at the bottom, which catches a typo in the literals.
"""

from __future__ import annotations

import json
import sys
from decimal import ROUND_HALF_UP, Decimal
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from openstore.sidecar.core.canonical import (  # noqa: E402
    cart_hash,
    pii_commit,
    quote_hash,
)

OUT = Path("tests/GOLDEN/cart_hash/vectors.json")

#: A fixed test salt. Real salts are `secrets.token_bytes(16)` generated by the
#: Merchant at `orders.create` (§16.1, §6.3a); this one exists so the vectors
#: reproduce, and it must never appear in a deployment.
TEST_SALT = bytes.fromhex("00112233445566778899aabbccddeeff")

MERCHANT_DOMAIN = "spoiledduckie.localhost"  # §16.1
EXPIRY_UTC = "2026-09-21T12:00:00Z"

# §16.5. The field names are a ladder-4 decision (logged under `## OPEN — h0`):
# the plan pins the addresses as prose and never names the object's shape.
DESTINATION_A = {
    "line1": "4th Cross, Indiranagar",
    "city": "Bengaluru",
    "state": "KA",
    "postal_code": "560038",
    "country": "IN",
}
DESTINATION_B = {
    "line1": "Dadar West",
    "city": "Mumbai",
    "state": "MH",
    "postal_code": "400028",
    "country": "IN",
}
CONTACT = {"email": "demo@spoiledduckie.test", "phone": "+919000000001"}

ZONE_KA = {"id": "karnataka", "label": "Karnataka", "cost_minor": 4900, "eta_days": 2}
ZONE_ROI = {"id": "rest-of-india", "label": "Rest of India", "cost_minor": 9900, "eta_days": 5}


def _line(
    sku: str,
    qty: int,
    unit: int,
    total: int,
    hsn: str,
    rate_bp: int,
    pos: str,
    addons: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    return {
        "sku": sku,
        "qty": qty,
        "unit_price_minor": unit,
        "line_total_minor": total,
        "hsn_sac": hsn,
        "gst_rate_bp": rate_bp,
        "place_of_supply": pos,
        "addons": addons or [],
    }


def _tax(kind: str, label: str, rate_bp: int, amount: int) -> dict[str, Any]:
    # Everything seeded is tax-inclusive (§16.11), so every tax line is
    # informational and is never added to the total — it reports what is
    # already inside it. Getting this backwards double-charges every order.
    return {
        "kind": kind,
        "label": label,
        "rate_bp": rate_bp,
        "amount_minor": amount,
        "informational": True,
    }


# 1 — minimal: SD-STICKERS ×1 to destination A.
#    19900 + 4900 shipping = 24800 inclusive on one line at 18%.
#    tax = 24800 × 1800 / 11800 = 3783.05 → 3783; CGST 1891, SGST 1892.
#    The odd paise goes to SGST, always (§16.11 step 6).
QUOTE_MINIMAL: dict[str, Any] = {
    "currency": "INR",
    "subtotal_minor": 19900,
    "lines": [_line("SD-STICKERS", 1, 19900, 19900, "4911", 1800, "KA")],
    "discount_lines": [],
    "fulfillment_options": [ZONE_KA],
    "fulfillment_chosen": {"id": "karnataka", "cost_minor": 4900},
    "tax_lines": [
        _tax("CGST", "CGST 9%", 900, 1891),
        _tax("SGST", "SGST 9%", 900, 1892),
    ],
    "round_off_minor": 0,
    "total_minor": 24800,
    "tax_inclusive": True,
}

# 2 — the §16.11 worked example. Numbers pinned there, copied here.
#     L1 99800 (tote + gift-wrap folded in), POS MH → IGST
#     L2 150000 (charm-bar seat, a service performed in KA) → CGST/SGST
#     shipping 9900 apportioned 3955 / 5945 (leftover paise to the larger fraction)
#     L1 103755 → IGST 15827   L2 155945 → tax 23788 → CGST 11894 / SGST 11894
QUOTE_MIXED: dict[str, Any] = {
    "currency": "INR",
    "subtotal_minor": 249800,
    "lines": [
        _line(
            "SD-TOTE-BLK-M",
            1,
            89900,
            99800,
            "4202",
            1800,
            "MH",
            addons=[{"sku": "SD-GIFTWRAP", "amount_minor": 9900}],
        ),
        _line("SD-CHARMBAR-SEAT", 1, 150000, 150000, "999799", 1800, "KA"),
    ],
    "discount_lines": [],
    "fulfillment_options": [ZONE_ROI],
    "fulfillment_chosen": {"id": "rest-of-india", "cost_minor": 9900},
    "tax_lines": [
        _tax("IGST", "IGST 18%", 1800, 15827),
        _tax("CGST", "CGST 9%", 900, 11894),
        _tax("SGST", "SGST 9%", 900, 11894),
    ],
    "round_off_minor": 0,
    "total_minor": 259700,
    "tax_inclusive": True,
}

# 3 — with a discount, two rates, destination A.
#     subtotal 134800 = tote 89900 (18%) + phone charm 44900 (3%)
#     SPOILED10 −10000 apportioned by line inclusive total: 6669.13 / 3330.86
#       → floor 6669 + 3330 = 9999, leftover paise to the larger fraction (L2)
#       → L1 −6669, L2 −3331
#     shipping 4900 on the same basis: 3267.87 / 1632.12
#       → floor 3267 + 1632 = 4899, leftover paise to L1 → L1 3268, L2 1632
#     L1 89900 − 6669 + 3268 = 86499 → tax 13195 → CGST 6597 / SGST 6598
#     L2 44900 − 3331 + 1632 = 43201 → tax  1258 → CGST  629 / SGST  629
QUOTE_DISCOUNT: dict[str, Any] = {
    "currency": "INR",
    "subtotal_minor": 134800,
    "lines": [
        _line("SD-TOTE-BLK-M", 1, 89900, 89900, "4202", 1800, "KA"),
        _line("SD-PHONECHARM", 1, 44900, 44900, "7117", 300, "KA"),
    ],
    "discount_lines": [{"label": "Launch code", "code": "SPOILED10", "amount_minor": -10000}],
    "fulfillment_options": [ZONE_KA],
    "fulfillment_chosen": {"id": "karnataka", "cost_minor": 4900},
    "tax_lines": [
        _tax("CGST", "CGST 9%", 900, 6597),
        _tax("SGST", "SGST 9%", 900, 6598),
        _tax("CGST", "CGST 1.5%", 150, 629),
        _tax("SGST", "SGST 1.5%", 150, 629),
    ],
    "round_off_minor": 0,
    "total_minor": 129700,
    "tax_inclusive": True,
}

CASES: list[dict[str, Any]] = [
    {
        "name": "minimal",
        "note": "one line, destination A, odd-paise CGST/SGST split",
        "quote": QUOTE_MINIMAL,
        "destination": DESTINATION_A,
        "lines": [{"sku": "SD-STICKERS", "qty": 1, "price_minor": 19900}],
        "fulfillment_option_id": "karnataka",
    },
    {
        "name": "mixed-basket",
        "note": "SPECS/PLAN.md §16.11 worked example — IGST and CGST/SGST in one Quote",
        "quote": QUOTE_MIXED,
        "destination": DESTINATION_B,
        "lines": [
            {"sku": "SD-TOTE-BLK-M", "qty": 1, "price_minor": 89900},
            {"sku": "SD-GIFTWRAP", "qty": 1, "price_minor": 9900},
            {"sku": "SD-CHARMBAR-SEAT", "qty": 1, "price_minor": 150000},
        ],
        "fulfillment_option_id": "rest-of-india",
    },
    {
        "name": "with-discount",
        "note": "SPOILED10 across two GST rates, largest-remainder on discount and shipping",
        "quote": QUOTE_DISCOUNT,
        "destination": DESTINATION_A,
        "lines": [
            {"sku": "SD-TOTE-BLK-M", "qty": 1, "price_minor": 89900},
            {"sku": "SD-PHONECHARM", "qty": 1, "price_minor": 44900},
        ],
        "fulfillment_option_id": "karnataka",
    },
]


def check_quote_identities(q: dict[str, Any], name: str) -> None:
    """§16.11 step 8, asserted so a typo in the literals above cannot ship.

    An Add-on folds into its parent's `line_total_minor` and is never a Quote
    Line of its own, so the subtotal identity is over `line_total_minor`.
    """
    subtotal = sum(ln["line_total_minor"] for ln in q["lines"])
    assert subtotal == q["subtotal_minor"], f"{name}: subtotal {subtotal} != {q['subtotal_minor']}"

    for ln in q["lines"]:
        folded = ln["qty"] * ln["unit_price_minor"] + sum(a["amount_minor"] for a in ln["addons"])
        assert folded == ln["line_total_minor"], f"{name}: line {ln['sku']} does not fold"

    discounts = sum(d["amount_minor"] for d in q["discount_lines"])
    assert discounts <= 0, f"{name}: a discount must be negative, sign is intrinsic"

    total = subtotal + q["fulfillment_chosen"]["cost_minor"] + discounts + q["round_off_minor"]
    assert total == q["total_minor"], f"{name}: total {total} != {q['total_minor']}"

    assert q["round_off_minor"] == 0, f"{name}: round_off is always 0 in v1 (§16.11 step 7)"

    # Tax is inclusive, so it is reported and never added. Every line's rate must
    # extract to the tax the Quote claims for it, by exact decimal arithmetic.
    assert q["tax_inclusive"] is True, f"{name}: the seeded Merchant is tax-inclusive"
    claimed = sum(t["amount_minor"] for t in q["tax_lines"])
    assert all(
        t["informational"] for t in q["tax_lines"]
    ), f"{name}: inclusive tax is informational"
    assert claimed < q["total_minor"], f"{name}: tax cannot exceed the total it sits inside"


def extract_tax(inclusive_minor: int, rate_bp: int) -> int:
    """§16.11 step 5, exact decimal, never binary float."""
    value = Decimal(inclusive_minor) * Decimal(rate_bp) / Decimal(10000 + rate_bp)
    return int(value.quantize(Decimal("1"), rounding=ROUND_HALF_UP))


def main() -> int:
    vectors = []
    for case in CASES:
        check_quote_identities(case["quote"], case["name"])
        qh = quote_hash(case["quote"])
        dh = pii_commit(TEST_SALT, case["destination"])
        ch = pii_commit(TEST_SALT, CONTACT)
        vectors.append(
            {
                "name": case["name"],
                "note": case["note"],
                "inputs": {
                    "lines": case["lines"],
                    "quote": case["quote"],
                    "destination": case["destination"],
                    "contact": CONTACT,
                    "order_salt_hex": TEST_SALT.hex(),
                    "fulfillment_option_id": case["fulfillment_option_id"],
                    "merchant_domain": MERCHANT_DOMAIN,
                    "expiry_utc": EXPIRY_UTC,
                },
                "expected": {
                    "quote_hash": qh,
                    "destination_hash": dh,
                    "contact_hash": ch,
                    "cart_hash": cart_hash(
                        lines=case["lines"],
                        quote_hash_hex=qh,
                        destination_hash=dh,
                        contact_hash=ch,
                        fulfillment_option_id=case["fulfillment_option_id"],
                        total_minor=case["quote"]["total_minor"],
                        currency=case["quote"]["currency"],
                        merchant_domain=MERCHANT_DOMAIN,
                        expiry_utc=EXPIRY_UTC,
                    ),
                },
            }
        )

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps({"vectors": vectors}, indent=2, ensure_ascii=False) + "\n")
    print(f"wrote {OUT} — {len(vectors)} vectors")
    for v in vectors:
        print(f"  {v['name']:<14} cart_hash {v['expected']['cart_hash']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
