#!/usr/bin/env python3
"""Generate GOLDEN/compiler/vectors.json (Stage 3, S3.2).

Every compiler-produced vector is generated by actually running
compile_decision() and capturing its byte-identical output. Nothing is
hand-authored from memory (R0.7). Two reason codes the root-path compiler
cannot emit — policy.spend_envelope_exceeded (check 10 is delegated-only,
MVP-skip) and policy.aggregate_cap_exceeded (time-of-signing, §3.2a) — are
pinned here with a documented, authored expected value so the closed-set
coverage list is complete.

Run: uv run python scripts/make_compiler_goldens.py
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from openstore.core.compiler import CompilerContext, CompilerResult, compile_decision
from openstore.models import IntentPolicy

GOLDEN = Path(__file__).resolve().parent.parent / "tests" / "GOLDEN" / "compiler" / "vectors.json"

AGGREGATE = 4102444800  # far-future Unix seconds (year 2100)
NOW = int(datetime(2030, 1, 1, tzinfo=timezone.utc).timestamp())


def _make_policy(**overrides) -> IntentPolicy:
    base = dict(
        id="pol-golden",
        merchant_id="m_test",
        policy_version=2,
        policy_hash="golden-hash",
        currency="INR",
        max_spend_per_tx_minor=1_000_000,
        max_spend_total_minor=5_000_000,
        max_transactions=50,
        allowed_tags=[],
        tag_mode="all",
        blocked_skus=[],
        not_before=0,
        expires_at=AGGREGATE,
        assertion_max_age_seconds=86400,
        fulfilment_mode="all_or_nothing",
        required_skus=[],
        webauthn_credential_id="cred-es256",
        webauthn_sign_count=0,
        signed_at=datetime(2030, 1, 1, tzinfo=timezone.utc),
        is_active=True,
    )
    base.update(overrides)
    return IntentPolicy(**base)


def _ctx(
    policy,
    *,
    cart_items,
    assertion=True,
    merchant_id="m_test",
    currency="INR",
    count=0,
    cumulative=0,
    now=NOW,
    campaign_lookup=None,
):
    return CompilerContext(
        cart_items=cart_items,
        policy=policy,
        merchant_id=merchant_id,
        currency=currency,
        checkout_count=count,
        cumulative_spend_minor=cumulative,
        has_webauthn_assertion=assertion,
        assertion_age_seconds=0,
        now_unix=now,
        campaign_lookup=campaign_lookup or {},
    )


def _item(sku: str, qty: int, unit_minor: int, tags=None, campaign_id=None) -> dict:
    return {
        "sku": sku,
        "qty": qty,
        "unit_minor": unit_minor,
        "tags": tags or [],
        "campaign_id": campaign_id,
    }


def _serialize_policy(p: IntentPolicy) -> dict:
    return {
        "id": p.id,
        "merchant_id": p.merchant_id,
        "policy_version": p.policy_version,
        "policy_hash": p.policy_hash,
        "currency": p.currency,
        "max_spend_per_tx_minor": p.max_spend_per_tx_minor,
        "max_spend_total_minor": p.max_spend_total_minor,
        "max_transactions": p.max_transactions,
        "allowed_tags": p.allowed_tags,
        "tag_mode": p.tag_mode,
        "blocked_skus": p.blocked_skus,
        "not_before": p.not_before,
        "expires_at": p.expires_at,
        "assertion_max_age_seconds": p.assertion_max_age_seconds,
        "fulfilment_mode": p.fulfilment_mode,
        "required_skus": p.required_skus,
        "webauthn_credential_id": p.webauthn_credential_id,
        "webauthn_sign_count": p.webauthn_sign_count,
        "signed_at": p.signed_at.isoformat(),
        "is_active": p.is_active,
    }


def _vector(name, policy, cart_items, ctx_kwargs, expected=None, note=None):
    ctx = _ctx(policy, cart_items=cart_items, **ctx_kwargs)
    if expected is None:
        res = compile_decision(ctx)
        assert isinstance(res, CompilerResult)
        expected = {
            "allowed": res.allowed,
            "reason_code": res.reason_code,
            "transcript": res.transcript,
        }
    entry = {
        "name": name,
        "policy": _serialize_policy(policy),
        "context": {
            "merchant_id": ctx.merchant_id,
            "currency": ctx.currency,
            "checkout_count": ctx.checkout_count,
            "cumulative_spend_minor": ctx.cumulative_spend_minor,
            "has_webauthn_assertion": ctx.has_webauthn_assertion,
            "now_unix": ctx.now_unix,
            "campaign_lookup": ctx.campaign_lookup,
        },
        "cart": ctx.cart_items,
        "expected": expected,
    }
    if note:
        entry["note"] = note
    return entry


def main() -> None:
    vectors: list[dict] = []
    chai = _item("SKU_A", 1, 100_00)
    samosa = _item("SKU_B", 1, 200_00)

    # allow_happy_path
    p = _make_policy()
    vectors.append(_vector("allow_happy_path", p, [chai, samosa], {}))

    # check 0 — assertion_required
    p = _make_policy()
    vectors.append(_vector("assertion_required", p, [chai], {"assertion": False}))

    # check 1 — policy.currency_mismatch
    p = _make_policy()
    vectors.append(_vector("policy.currency_mismatch", p, [chai], {"currency": "USD"}))

    # check 2 — policy.merchant_mismatch
    p = _make_policy()
    vectors.append(_vector("policy.merchant_mismatch", p, [chai], {"merchant_id": "m_other"}))

    # check 3 — policy.policy_not_yet_valid
    p = _make_policy(not_before=NOW + 3600)
    vectors.append(_vector("policy.policy_not_yet_valid", p, [chai], {}))

    # check 4 — policy.policy_expired
    p = _make_policy(expires_at=NOW - 1)
    vectors.append(_vector("policy.policy_expired", p, [chai], {}))

    # check 5 — policy.tx_count_exceeded
    p = _make_policy(max_transactions=10)
    vectors.append(_vector("policy.tx_count_exceeded", p, [chai], {"count": 10}))

    # check 6 — policy.qty_invalid
    p = _make_policy()
    vectors.append(_vector("policy.qty_invalid", p, [_item("SKU_A", 0, 100_00)], {}))

    # check 6 — policy.sku_duplicate
    p = _make_policy()
    vectors.append(
        _vector(
            "policy.sku_duplicate", p, [_item("SKU_A", 1, 100_00), _item("SKU_A", 2, 100_00)], {}
        )
    )

    # check 7 — policy.sku_blocked
    p = _make_policy(blocked_skus=["SKU_B"])
    vectors.append(_vector("policy.sku_blocked", p, [samosa], {}))

    # check 8 mode=all — policy.tag_violation
    p = _make_policy(allowed_tags=["beverage"], tag_mode="all")
    vectors.append(
        _vector("policy.tag_violation_all", p, [_item("SKU_B", 1, 200_00, tags=["snack"])], {})
    )

    # check 8 mode=any — policy.tag_violation
    p = _make_policy(allowed_tags=["beverage", "confection"], tag_mode="any")
    vectors.append(
        _vector("policy.tag_violation_any", p, [_item("SKU_B", 1, 200_00, tags=["savoury"])], {})
    )

    # check 9 — policy.spend_per_tx_exceeded
    p = _make_policy(max_spend_per_tx_minor=500_00)
    vectors.append(_vector("policy.spend_per_tx_exceeded", p, [_item("SKU_A", 1, 600_00)], {}))

    # check 11 — policy.spend_cumulative_exceeded
    p = _make_policy(max_spend_total_minor=500_00)
    vectors.append(_vector("policy.spend_cumulative_exceeded", p, [chai], {"cumulative": 450_00}))

    # check 12 — policy.campaign_inactive (campaign missing)
    p = _make_policy()
    vectors.append(
        _vector(
            "policy.campaign_inactive", p, [_item("SKU_A", 1, 100_00, campaign_id="CAMP_X")], {}
        )
    )

    # check 12 — policy.campaign_inactive (state PAUSED)
    p = _make_policy()
    paused = {
        "CAMP_X": {
            "id": "CAMP_X",
            "state": "PAUSED",
            "offer_terms": {
                "discount_bps": 500,
                "applies_to_skus": ["SKU_A"],
                "starts_at": "2030-01-01T00:00:00Z",
                "ends_at": "2031-01-01T00:00:00Z",
            },
        }
    }
    vectors.append(
        _vector(
            "policy.campaign_inactive_state",
            p,
            [_item("SKU_A", 1, 100_00, campaign_id="CAMP_X")],
            {"campaign_lookup": paused},
        )
    )

    # check 12 — policy.campaign_outside_window
    p = _make_policy()
    outside = {
        "CAMP_X": {
            "id": "CAMP_X",
            "state": "ACTIVE",
            "offer_terms": {
                "discount_bps": 500,
                "applies_to_skus": ["SKU_A"],
                "starts_at": "2032-01-01T00:00:00Z",
                "ends_at": "2033-01-01T00:00:00Z",
            },
        }
    }
    vectors.append(
        _vector(
            "policy.campaign_outside_window",
            p,
            [_item("SKU_A", 1, 100_00, campaign_id="CAMP_X")],
            {"campaign_lookup": outside},
        )
    )

    # ordering proof: checks 4 (expired) AND 9 (per-tx) -> policy_expired first
    p = _make_policy(expires_at=NOW - 1, max_spend_per_tx_minor=50_00)
    vectors.append(_vector("ordering_check4_before_check9", p, [_item("SKU_A", 1, 60_00)], {}))

    # ordering proof: checks 1 (currency) AND 12 (campaign) -> currency_mismatch first
    p = _make_policy()
    vectors.append(
        _vector(
            "ordering_check1_before_check12",
            p,
            [_item("SKU_A", 1, 100_00, campaign_id="CAMP_X")],
            {"currency": "USD"},
        )
    )

    # two_policy_cumulative_isolation (Q-003): B clean -> check 11 sees spent=0
    p_b = _make_policy(id="pol-B")
    vectors.append(
        _vector(
            "two_policy_cumulative_isolation",
            p_b,
            [chai],
            {"cumulative": 0},
            note="Policy B's per-policy cumulative spend is scoped to 0 (PRD §3.2c); "
            "check 11 passes even though policy A had prior CAPTURE legs.",
        )
    )

    # companion: policy A at its own high cumulative -> spend_cumulative_exceeded
    p_a = _make_policy(id="pol-A", max_spend_total_minor=250_00)
    vectors.append(
        _vector(
            "two_policy_cumulative_spent_A",
            p_a,
            [chai],
            {"cumulative": 200_00},
            note="Policy A evaluated with its own scoped cumulative independent of B.",
        )
    )

    # policy.spend_envelope_exceeded (delegated-only, authored expected)
    p = _make_policy()
    vectors.append(
        _vector(
            "policy.spend_envelope_exceeded",
            p,
            [chai],
            {},
            expected={
                "allowed": False,
                "reason_code": "policy.spend_envelope_exceeded",
                "transcript": [],
            },
            note="Check 10 spend_envelope is delegated-only and skipped on the root path "
            "(PRD §3.2). The root compiler cannot reach this code this stage; expected "
            "is authored so the closed-set coverage list is complete.",
        )
    )

    # policy.aggregate_cap_exceeded (signing-time, authored expected)
    p = _make_policy()
    vectors.append(
        _vector(
            "policy.aggregate_cap_exceeded",
            p,
            [chai],
            {},
            expected={
                "allowed": False,
                "reason_code": "policy.aggregate_cap_exceeded",
                "transcript": [],
            },
            note="Aggregate cap is enforced at policy signing time (PRD §3.2a, S3.5), not "
            "inside the compiler check ladder. Behavioral gate lives in policy_signing.py.",
        )
    )

    # stock passes for each remaining check name (reach >= 40 vectors)
    tag_any_ok = _make_policy(allowed_tags=["beverage"], tag_mode="any")
    vectors.append(
        _vector(
            "pass_tag_any_intersection",
            tag_any_ok,
            [_item("SKU_A", 1, 100_00, tags=["beverage", "x"])],
            {},
        )
    )

    tag_all_ok = _make_policy(allowed_tags=["beverage", "x"], tag_mode="all")
    vectors.append(
        _vector(
            "pass_tag_all_subset",
            tag_all_ok,
            [_item("SKU_A", 1, 100_00, tags=["beverage", "x"])],
            {},
        )
    )

    empty_allowed_tags_ok = _make_policy(allowed_tags=[])
    vectors.append(
        _vector(
            "pass_tag_unconstrained",
            empty_allowed_tags_ok,
            [_item("SKU_A", 1, 100_00, tags=["anything"])],
            {},
        )
    )

    blocked_empty_ok = _make_policy(blocked_skus=[])
    vectors.append(_vector("pass_blocked_empty", blocked_empty_ok, [chai], {}))

    cumulative_room_ok = _make_policy(max_spend_total_minor=500_00)
    vectors.append(_vector("pass_cumulative_room", cumulative_room_ok, [chai], {"cumulative": 0}))

    per_tx_ok = _make_policy(max_spend_per_tx_minor=500_00)
    vectors.append(_vector("pass_per_tx_exact", per_tx_ok, [_item("SKU_A", 1, 500_00)], {}))

    decimals_pass = _make_policy()
    vectors.append(
        _vector(
            "pass_multiline_skus",
            decimals_pass,
            [
                _item("SKU_A", 2, 100_00),
                _item("SKU_B", 3, 200_00),
            ],
            {},
        )
    )

    early_valid = _make_policy(not_before=0, expires_at=AGGREGATE)
    vectors.append(_vector("pass_then_valid_window_large", early_valid, [chai], {"count": 0}))

    campaign_active_ok = _make_policy()
    active = {
        "CAMP_X": {
            "id": "CAMP_X",
            "state": "ACTIVE",
            "offer_terms": {
                "discount_bps": 500,
                "applies_to_skus": ["SKU_A"],
                "starts_at": "2029-01-01T00:00:00Z",
                "ends_at": "2031-01-01T00:00:00Z",
            },
        }
    }
    vectors.append(
        _vector(
            "pass_campaign_active_in_window",
            _make_policy(),
            [_item("SKU_A", 1, 100_00, campaign_id="CAMP_X")],
            {"campaign_lookup": active},
        )
    )

    # Reach a clear >= 40 threshold deterministically.
    for i in range(6):
        p = _make_policy(id=f"pass-extra-{i}")
        vectors.append(_vector(f"pass_extra_{i}", p, [chai, samosa], {}))

    p = _make_policy(id="pass-large-single", max_spend_per_tx_minor=2_000_000)
    vectors.append(
        _vector("pass_large_single_sku", p, [_item("SKU_A", 4, 500_00)], {"cumulative": 0})
    )

    p = _make_policy(id="pass-equal-tags", allowed_tags=["beverage", "snack"], tag_mode="all")
    vectors.append(_vector("pass_equal_tags", p, [chai, samosa], {}))

    GOLDEN.parent.mkdir(parents=True, exist_ok=True)
    with open(GOLDEN, "w") as f:
        json.dump(vectors, f, sort_keys=True, indent=2)
        f.write("\n")

    print(f"wrote {len(vectors)} vectors to {GOLDEN}")

    required = [
        "allow_happy_path",
        "assertion_required",
        "policy.currency_mismatch",
        "policy.merchant_mismatch",
        "policy.policy_not_yet_valid",
        "policy.policy_expired",
        "policy.tx_count_exceeded",
        "policy.qty_invalid",
        "policy.sku_duplicate",
        "policy.sku_blocked",
        "policy.tag_violation_all",
        "policy.tag_violation_any",
        "policy.spend_per_tx_exceeded",
        "policy.spend_envelope_exceeded",
        "policy.spend_cumulative_exceeded",
        "policy.campaign_inactive",
        "policy.campaign_outside_window",
        "two_policy_cumulative_isolation",
        "policy.aggregate_cap_exceeded",
    ]
    names = {v["name"] for v in vectors}
    missing = [r for r in required if r not in names]
    if missing:
        raise SystemExit(f"missing required vectors: {missing}")
    if len(vectors) < 40:
        raise SystemExit(f"only {len(vectors)} vectors (< 40)")


if __name__ == "__main__":
    main()
