#!/usr/bin/env python3
"""Generate `docs/CODES.md` from the enums in `core/codes.py`, and diff it.

The enums are the registry; the doc is a rendering of them. `--check` prints
nothing and exits 0 when the two agree, and exits 1 with a diff when they do
not, so CI goes red the moment somebody edits the doc instead of the enum.

`--prose` additionally reports identifiers that read like closed-set members in
the spec prose but exist in no enum (SPEC §12: "a code named in prose but
missing from the registry is a red build"). It is advisory here and wired into
CI by A1.

Ported from `main`'s `scripts/registry_diff.py`, which diffed raised codes
against a hand-maintained `REGISTRY.json`. The direction is reversed: there is
no hand-maintained file left to drift.
"""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from enum import StrEnum
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from openstore.sidecar.core.codes import (  # noqa: E402
    CLOSED_SETS,
    DISPATCHABLE_STATUSES,
    GATE_CHECK_ORDER,
    HTTP_STATUS,
    TOOL_SCOPES,
    ReasonCode,
)

_DOC = Path("docs/CODES.md")

_HEADER = """<!-- GENERATED BY scripts/registry_diff.py — DO NOT EDIT BY HAND. -->
<!-- The enums in src/openstore/sidecar/core/codes.py are the registry; this -->
<!-- file is a rendering of them. Edit the enum, then run the script. -->

# Closed sets

Every identifier the system is allowed to use. A code named in prose but absent
here is a red build (SPEC §12). Generated from `core/codes.py`, diffed in CI.
"""


def render() -> str:
    out = [_HEADER]

    for title, enum_cls in CLOSED_SETS.items():
        members = [m.value for m in enum_cls]
        out.append(f"\n## {title} ({len(members)})\n")
        out.append("\n".join(f"- `{v}`" for v in members) + "\n")

    out.append("\n## Reason code → HTTP status\n")
    out.append("The call site never chooses a status; this table does.\n")
    out.append("\n| Reason code | HTTP |\n|---|---|\n")
    out.append("".join(f"| `{c.value}` | {HTTP_STATUS[c]} |\n" for c in ReasonCode))

    out.append("\n## Tool name → scope required\n")
    out.append("\n| Tool | Scope |\n|---|---|\n")
    out.append("".join(f"| `{t.value}` | `{s.value}` |\n" for t, s in TOOL_SCOPES.items()))

    out.append("\n## The Gate's fixed check order\n")
    out.append(
        "`decide()` runs these in order, stopping at the first failure. The\n"
        "Transcript's bytes depend on the order, so it is not reordered for\n"
        "tidiness (SPEC \u00a74).\n\n"
    )
    out.append("\n".join(f"{i}. `{c.value}`" for i, c in enumerate(GATE_CHECK_ORDER, 1)) + "\n")

    out.append("\n## Statuses a dispatch may be recorded on\n")
    out.append(
        "Dispatch assigns the gapless `invoice_number`, so it is refused on a\n"
        "terminal-negative status with `dispatch-not-allowed` (ADR-0020).\n\n"
    )
    out.append("\n".join(f"- `{s.value}`" for s in sorted(DISPATCHABLE_STATUSES)) + "\n")

    return "".join(out)


def _all_members() -> set[str]:
    known: set[str] = set()
    for enum_cls in CLOSED_SETS.values():
        assert issubclass(enum_cls, StrEnum)
        known.update(m.value for m in enum_cls)
    return known


#: Hyphenated prose that is deliberately not a closed-set member. Each entry is
#: a phrase the spec uses as English or as a field/flag name, not as a code.
#: Kept explicit rather than pattern-matched: an allowlist that is a regex stops
#: being reviewable.
_NOT_CODES = frozenset(
    {
        "adapter-node",  # a SvelteKit package name
        "agent-commerce",  # /.well-known/agent-commerce.json
        "cash-on-delivery",  # a payment method, registered as one
        "compare-and-set",
        "continue-selling-when-out-of-stock",
        "cross-device",
        "demo-admin",  # a component, not a code
        "direct-add",
        "direct-checkout",
        "enroll-and-tap",
        "hold-stock",
        "in-agent",
        "order-lookup",
        "per-line",
        "per-order",
        "post-application",
        "pre-money",
        "proof-carrying",
        "read-then-act",
        "refund-requested",  # a queue state on the Merchant side, not a refusal
        "resolve-then-pin",
        "rest-of-india",  # a seeded fulfillment option id (§16.5)
        "self-hosted",
        "self-registered",
        "shop-ops",
        "side-effect-free",
        "single-use",
        "site-direct",
        "tax-inclusive",
        "time-boxed",
        "two-per-order",
        "well-known",
    }
)


#: The files prose is held to. `docs/` carries review findings, drafts and
#: decision logs — historical records that name codes which were considered and
#: rejected (`upi-block`, `method-not-entitled`). Scanning them would force an
#: allowlist of dead terms, which is a worse lie than not scanning them.
def _NORMATIVE() -> list[Path]:
    return [
        p
        for p in (Path("SPEC.md"), Path("CONTEXT.md"), *sorted(Path(".").glob("PLAN*.md")))
        if p.exists()
    ]


_TOKEN = re.compile(r"`([a-z][a-z0-9]*(?:-[a-z0-9]+)+)`")


def check_prose(paths: list[Path]) -> int:
    """Report backticked hyphen-lowercase tokens that are in no closed set."""
    known = _all_members() | _NOT_CODES
    unknown: dict[str, list[str]] = {}
    for path in paths:
        for token in _TOKEN.findall(path.read_text(encoding="utf-8")):
            if token not in known:
                unknown.setdefault(token, []).append(path.name)
    for token, where in sorted(unknown.items()):
        print(f"PROSE {token!r} is in no closed set — {', '.join(sorted(set(where)))}")
    return 1 if unknown else 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 if the doc is stale")
    ap.add_argument("--prose", action="store_true", help="also scan spec prose (advisory)")
    args = ap.parse_args()

    rendered = render()

    if args.check:
        current = _DOC.read_text(encoding="utf-8") if _DOC.exists() else ""
        if current != rendered:
            print(f"{_DOC} is stale — regenerate with: uv run scripts/registry_diff.py")
            sys.stdout.writelines(
                difflib.unified_diff(
                    current.splitlines(keepends=True),
                    rendered.splitlines(keepends=True),
                    fromfile=f"{_DOC} (on disk)",
                    tofile="generated from codes.py",
                )
            )
            return 1
    else:
        _DOC.parent.mkdir(parents=True, exist_ok=True)
        _DOC.write_text(rendered, encoding="utf-8")

    if args.prose:
        return check_prose(_NORMATIVE())

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
