/**
 * The fetcher, against the card the sidecar actually serves.
 *
 * `contacts.test.ts` builds its own cards, so it passed while the fetcher
 * agreed with nothing: the real card carries no inline `jwks`, and every
 * attempt to add a real shop was refused. These fixtures are the sidecar's own
 * golden output (`tests/GOLDEN/card/`, generated by `scripts/make_card_golden.py`
 * and asserted by `tests/test_card_golden.py`), read from one place by both
 * sides so neither can drift alone.
 */
import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { fetchCard, parseCard } from '../src/lib/contacts.ts';

const GOLDEN = fileURLToPath(new URL('../../../tests/GOLDEN/card/', import.meta.url));
const read = (name: string) => readFileSync(GOLDEN + name, 'utf8');

const CARD = read('agent-commerce.json');
const JWKS = read('jwks.json');
const DOMAIN = 'spoiledduckie.localhost';
const CARD_URL = `http://${DOMAIN}/.well-known/agent-commerce.json`;

// The demo's own exception, named exactly as compose names it: the shop is
// plain http on a private address.
process.env.OPENSTORE_DEV_PROFILE_HOSTS = DOMAIN;
const resolver = async () => ['172.18.0.3'];

/** Serves the two real documents and nothing else; anything unexpected 404s. */
const sidecar = (documents: Record<string, string>) =>
	(async (url: string) => {
		const path = new URL(url).pathname;
		return path in documents
			? new Response(documents[path], { status: 200 })
			: new Response('not found', { status: 404 });
	}) as unknown as typeof fetch;

const live = sidecar({
	'/.well-known/agent-commerce.json': CARD,
	'/.well-known/jwks.json': JWKS
});

describe('the card the sidecar really serves', () => {
	it('is added, keys and all', async () => {
		const card = await fetchCard(CARD_URL, live, resolver);
		expect(card.name).toBe('SpoiledDuckie');
		expect(card.domain).toBe(DOMAIN);
		expect(card.protocols).toEqual(['mcp', 'ucp', 'ap2', 'acp']);
		// The keys came from the second document, not from the card.
		expect(card.jwksUrl).toBe(`http://${DOMAIN}/.well-known/jwks.json`);
		expect(card.jwks.keys[0]?.kid).toBe('sd-2026-09');
	});

	it('reads the name from the merchant block, where the card puts it', () => {
		const meta = parseCard(JSON.parse(CARD), DOMAIN);
		expect(meta.name).toBe('SpoiledDuckie');
	});

	it('refuses a shop whose keys never answer, rather than pinning nothing', async () => {
		const noKeys = sidecar({ '/.well-known/agent-commerce.json': CARD });
		await expect(fetchCard(CARD_URL, noKeys, resolver)).rejects.toMatchObject({
			code: 'unreachable'
		});
	});

	it('refuses a card that sources its keys from somewhere else', () => {
		const stolen = JSON.parse(CARD);
		stolen.endpoints.jwks = 'https://attacker.example/.well-known/jwks.json';
		expect(() => parseCard(stolen, DOMAIN)).toThrow(/attacker\.example/);
	});

	it('refuses a card copied from another shop', () => {
		const copied = JSON.parse(CARD);
		copied.merchant.domain = 'someone-else.example';
		expect(() => parseCard(copied, DOMAIN)).toThrow(/someone-else\.example/);
	});
});
